version: '3.1'

services:
  db:
    container_name: "todoDB"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - ./mysqlData:/var/lib/mysql

  scheduler:
    container_name: "schedulerDB"
    image: mongo:5.0
    ports:
      - "27020:27017"
    restart: always
    volumes:
      - ./apschedulerDB:/etc/mongo
