version: '3.1'

services:
  db:
    image: postgres:12
    container_name: "bot_db"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME